
package com.verdicchio.factoryhomes.infrastructure.inventorysystem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventorySystemServiceImpl", targetNamespace = "InventorySystem", wsdlLocation = "http://localhost:8080/InventorySystem/InventorySystemServiceImpl?wsdl")
public class InventorySystemService_Service
    extends Service
{

    private final static URL INVENTORYSYSTEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException INVENTORYSYSTEMSERVICE_EXCEPTION;
    private final static QName INVENTORYSYSTEMSERVICE_QNAME = new QName("InventorySystem", "InventorySystemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/InventorySystem/InventorySystemService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYSYSTEMSERVICE_WSDL_LOCATION = url;
        INVENTORYSYSTEMSERVICE_EXCEPTION = e;
    }

    public InventorySystemService_Service() {
        super(__getWsdlLocation(), INVENTORYSYSTEMSERVICE_QNAME);
    }

    public InventorySystemService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYSYSTEMSERVICE_QNAME, features);
    }

    public InventorySystemService_Service(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYSYSTEMSERVICE_QNAME);
    }

    public InventorySystemService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYSYSTEMSERVICE_QNAME, features);
    }

    public InventorySystemService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventorySystemService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventorySystemServiceImpl
     */
    @WebEndpoint(name = "InventorySystem")
    public InventorySystemService getInventorySystem() {
        return super.getPort(new QName("InventorySystem", "InventorySystem"), InventorySystemService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventorySystemServiceImpl
     */
    @WebEndpoint(name = "InventorySystem")
    public InventorySystemService getInventorySystem(WebServiceFeature... features) {
        return super.getPort(new QName("InventorySystem", "InventorySystem"), InventorySystemService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYSYSTEMSERVICE_EXCEPTION!= null) {
            throw INVENTORYSYSTEMSERVICE_EXCEPTION;
        }
        return INVENTORYSYSTEMSERVICE_WSDL_LOCATION;
    }

}
