
package com.verdicchio.infrastracture.inventorysystem;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventorySystemService", targetNamespace = "InventorySystem")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventorySystemService {


    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkApplicability", targetNamespace = "InventorySystem", className = "inventorysystem.CheckApplicability")
    @ResponseWrapper(localName = "checkApplicabilityResponse", targetNamespace = "InventorySystem", className = "inventorysystem.CheckApplicabilityResponse")
    public Boolean checkApplicability();

    /**
     * 
     * @return
     *     returns java.util.List<inventorysystem.Category>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategory", targetNamespace = "InventorySystem", className = "inventorysystem.GetCategory")
    @ResponseWrapper(localName = "getCategoryResponse", targetNamespace = "InventorySystem", className = "inventorysystem.GetCategoryResponse")
    public List<Category> getCategory();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<inventorysystem.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemByCategory", targetNamespace = "InventorySystem", className = "inventorysystem.GetItemByCategory")
    @ResponseWrapper(localName = "getItemByCategoryResponse", targetNamespace = "InventorySystem", className = "inventorysystem.GetItemByCategoryResponse")
    public List<Item> getItemByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
